function header(element) {
  const header = document.createElement("header");
  header.classList.add("header");
  const logoHeader = document.createElement("a");
  logoHeader.classList.add("header__breadcrumbs");
  logoHeader.setAttribute("href", "index.html");
  header.appendChild(logoHeader);
  const logo = document.createElement("img");
  logo.setAttribute("src", "./src/img/main/logo.svg");
  logoHeader.appendChild(logo);
  const headerInput = document.createElement("input");
  headerInput.classList.add("header__input");
  headerInput.setAttribute("placeholder", "Поиск");
  header.appendChild(headerInput);
  const headerMenu = document.createElement("nav");
  headerMenu.classList.add("header__menu");
  header.appendChild(headerMenu);
  const headerCatalog = document.createElement("a");
  headerCatalog.classList.add("header__breadcrumbs");
  headerCatalog.textContent = "Каталог";
  headerCatalog.addEventListener('click', (event) => {
    event.preventDefault();
    window.application.screens['catalogScreen'] = catalogScreen;
    window.application.renderScreen('catalogScreen');
  });
  headerMenu.appendChild(headerCatalog);
  const headerCart = document.createElement("a");
  headerCart.classList.add("header__breadcrumbs");
  headerCart.setAttribute("href", "#");
  headerCart.textContent = "Корзина";
  headerMenu.appendChild(headerCart);
  return element.appendChild(header);
}

function mainBlock(container) {
  let mainBlockArray = [];
  const top = document.createElement("div");
  top.classList.add("top", "center");
  mainBlockArray.push(top);
  header(top);
  const mainTitle = document.createElement("h1");
  mainTitle.textContent = "Всё, чего заслуживает ваш дом.";
  mainTitle.classList.add("title");
  top.appendChild(mainTitle);
  const mainSubTitle = document.createElement("p");
  mainSubTitle.textContent = "Наша мебель - ваше отражение.";
  mainSubTitle.classList.add("subtitle");
  top.appendChild(mainSubTitle);
  const linkCatalog = document.createElement("a");
  linkCatalog.addEventListener('click', (event) => {
    event.preventDefault();
    window.application.screens['catalogScreen'] = catalogScreen;
    window.application.renderScreen('catalogScreen');
  });
  linkCatalog.textContent = "Перейти в каталог";
  linkCatalog.classList.add("catalog");
  top.appendChild(linkCatalog);
  const forBox = document.createElement("div");
  forBox.classList.add("for__box", "center");
  mainBlockArray.push(forBox);
  const forBoxTitle = document.createElement("p");
  forBoxTitle.textContent = "Мебель для ...";
  forBoxTitle.classList.add("for__box__title");
  forBox.appendChild(forBoxTitle);
  const forImage = document.createElement("div");
  forImage.classList.add("for");
  forBox.appendChild(forImage);
  const relaxImage = document.createElement("div");
  relaxImage.textContent = "ОТДЫХА";
  relaxImage.classList.add("for_item", "for_item_1", "for_item_big");
  forImage.appendChild(relaxImage);
  const workImage = document.createElement("div");
  workImage.textContent = "РАБОТЫ";
  workImage.classList.add("for_item", "for_item_2", "for_item_big");
  forImage.appendChild(workImage);
  const kitchenImage = document.createElement("div");
  kitchenImage.textContent = "КУХНИ";
  kitchenImage.classList.add("for_item", "for_item_3");
  forImage.appendChild(kitchenImage);
  const childrenRoomImage = document.createElement("div");
  childrenRoomImage.textContent = "ДЕТСКОЙ";
  childrenRoomImage.classList.add("for_item", "for_item_4");
  forImage.appendChild(childrenRoomImage);
  const bathroomImage = document.createElement("div");
  bathroomImage.textContent = "ВАННОЙ";
  bathroomImage.classList.add("for_item", "for_item_5");
  forImage.appendChild(bathroomImage);
  const productBox = document.createElement("div");
  productBox.classList.add("center");
  mainBlockArray.push(productBox);
  const productBoxTitle = document.createElement("p");
  productBoxTitle.textContent = "Специальные предложения";
  productBoxTitle.classList.add("product__box__title");
  productBox.appendChild(productBoxTitle);
  const specialOfferBox = document.createElement('div');
  specialOfferBox.classList.add('product_content');
  productBox.appendChild(specialOfferBox);
  const chandelierBox = document.createElement("div");
  chandelierBox.classList.add("product");
  specialOfferBox.appendChild(chandelierBox);
  icons(chandelierBox);
  const chandelierImage = document.createElement('img');
  chandelierImage.setAttribute('src', './src/img/main/voda__lustra.jpg');
  chandelierImage.classList.add('product_img');
  chandelierBox.appendChild(chandelierImage);
  const chandelierLink = document.createElement('a');
  chandelierLink.setAttribute('href', '#');
  chandelierBox.appendChild(chandelierLink);
  const chandelierName = document.createElement('p');
  chandelierName.textContent = 'Люстра VODA';
  chandelierName.classList.add('item');
  chandelierLink.appendChild(chandelierName);
  const chandelierInfo = document.createElement('p');
  chandelierInfo.textContent = 'Основание из полированной нержавеющей стали, придает оригинальный парящий эффект.';
  chandelierInfo.classList.add('desc');
  chandelierBox.appendChild(chandelierInfo);
  const boxPrice = document.createElement('div');
  boxPrice.classList.add('box__price');
  chandelierBox.appendChild(boxPrice);
  const price = document.createElement('p');
  price.textContent = '45 000 руб.';
  price.classList.add('price');
  boxPrice.appendChild(price);
  const priceSecond = document.createElement('p');
  priceSecond.textContent = '67 000 руб.';
  priceSecond.classList.add('price', 'price2');
  boxPrice.appendChild(priceSecond);
  const sofaBox = document.createElement("div");
  sofaBox.classList.add("product");
  specialOfferBox.appendChild(sofaBox);
  const sofaImage = document.createElement('img');
  sofaImage.setAttribute('src', './src/img/main/divan__ronald.jpg');
  sofaImage.classList.add('product_img');
  sofaBox.appendChild(sofaImage);
  const sofaLink = document.createElement('a');
  sofaLink.setAttribute('href', '#');
  sofaBox.appendChild(sofaLink);
  const sofaName = document.createElement('p');
  sofaName.textContent = 'Диван RONALD';
  sofaName.classList.add('item');
  sofaLink.appendChild(sofaName);
  const sofaInfo = document.createElement('p');
  sofaInfo.textContent = 'Модель отличается простотой линий и форм, отсутствием броского декора.';
  sofaInfo.classList.add('desc');
  sofaBox.appendChild(sofaInfo);
  const boxPriceSofa = document.createElement('div');
  boxPriceSofa.classList.add('box__price');
  sofaBox.appendChild(boxPriceSofa);
  const priceSofa = document.createElement('p');
  priceSofa.textContent = '156 000 руб.';
  priceSofa.classList.add('price');
  boxPriceSofa.appendChild(priceSofa);
  const priceSecondSofa = document.createElement('p');
  priceSecondSofa.textContent = '198 000 руб.';
  priceSecondSofa.classList.add('price', 'price2');
  boxPriceSofa.appendChild(priceSecondSofa);
  const dresserBox = document.createElement("div");
  dresserBox.classList.add("product");
  specialOfferBox.appendChild(dresserBox);
  const dresserImage = document.createElement('img');
  dresserImage.setAttribute('src', './src/img/main/komod__vent.jpg');
  dresserImage.classList.add('product_img');
  dresserBox.appendChild(dresserImage);
  const dresserLink = document.createElement('a');
  dresserLink.setAttribute('href', '#');
  dresserBox.appendChild(dresserLink);
  const dresserName = document.createElement('p');
  dresserName.textContent = 'Комод Vent';
  dresserName.classList.add('item');
  dresserLink.appendChild(dresserName);
  const dresserInfo = document.createElement('p');
  dresserInfo.textContent = 'Европейский дуб - отличается особой прочностью и стабильностью.';
  dresserInfo.classList.add('desc');
  dresserBox.appendChild(dresserInfo);
  const boxPriceDresser = document.createElement('div');
  boxPriceDresser.classList.add('box__price');
  dresserBox.appendChild(boxPriceDresser);
  const priceDresser = document.createElement('p');
  priceDresser.textContent = '34 000 руб.';
  priceDresser.classList.add('price');
  boxPriceDresser.appendChild(priceDresser);
  const priceSecondDresser = document.createElement('p');
  priceSecondDresser.textContent = '45 000 руб.';
  priceSecondDresser.classList.add('price', 'price2');
  boxPriceDresser.appendChild(priceSecondDresser);
  const productCatalog = document.createElement('div');
  productCatalog.classList.add('center');
  mainBlockArray.push(productCatalog);
  const productCatalogTitle = document.createElement('p');
  productCatalogTitle.textContent = 'Каталог товаров';
  productCatalogTitle.classList.add('product__box__title');
  productCatalog.appendChild(productCatalogTitle);
  const productCatalogBox = document.createElement('div');
  productCatalogBox.classList.add('product_content');
  productCatalog.appendChild(productCatalogBox);
  const badBox = document.createElement("div");
  badBox.classList.add("product");
  productCatalogBox.appendChild(badBox);
  icons(badBox);
  const badImage = document.createElement('img');
  badImage.setAttribute('src', './src/img/main/krovat__tatran.jpg');
  badImage.classList.add('product_img');
  badBox.appendChild(badImage);
  const badLink = document.createElement('a');
  badLink.setAttribute('href', '#');
  badBox.appendChild(badLink);
  const badName = document.createElement('p');
  badName.textContent = 'Кровать TATRAN';
  badName.classList.add('item');
  badLink.appendChild(badName);
  const badInfo = document.createElement('p');
  badInfo.textContent = 'Основание из полированной нержавеющей стали, придает оригинальный парящий эффект.';
  badInfo.classList.add('desc');
  badBox.appendChild(badInfo);
  const badBoxPrice = document.createElement('div');
  badBoxPrice.classList.add('box__price');
  badBox.appendChild(badBoxPrice);
  const badPrice = document.createElement('p');
  badPrice.textContent = '120 000 руб.';
  badPrice.classList.add('price');
  badBoxPrice.appendChild(badPrice);
  const sofaViloraBox = document.createElement("div");
  sofaViloraBox.classList.add("product");
  productCatalogBox.appendChild(sofaViloraBox);
  const sofaViloraImage = document.createElement('img');
  sofaViloraImage.setAttribute('src', './src/img/main/kreslo_vilora.jpg');
  sofaViloraImage.classList.add('product_img');
  sofaViloraBox.appendChild(sofaViloraImage);
  const sofaViloraLink = document.createElement('a');
  sofaViloraLink.setAttribute('href', '#');
  sofaViloraBox.appendChild(sofaViloraLink);
  const sofaViloraName = document.createElement('p');
  sofaViloraName.textContent = 'Кресло VILORA';
  sofaViloraName.classList.add('item');
  sofaViloraLink.appendChild(sofaViloraName);
  const sofaViloraInfo = document.createElement('p');
  sofaViloraInfo.textContent = 'Мягкое и уютное, аккуратное и стильное. Упругие подушки сиденья и приятная на ощупь ткань.';
  sofaViloraInfo.classList.add('desc');
  sofaViloraBox.appendChild(sofaViloraInfo);
  const sofaViloraBoxPrice = document.createElement('div');
  sofaViloraBoxPrice.classList.add('box__price');
  sofaViloraBox.appendChild(sofaViloraBoxPrice);
  const sofaViloraPrice = document.createElement('p');
  sofaViloraPrice.textContent = '21 000 руб.';
  sofaViloraPrice.classList.add('price');
  sofaViloraBoxPrice.appendChild(sofaViloraPrice);
  const tableBox = document.createElement("div");
  tableBox.classList.add("product");
  productCatalogBox.appendChild(tableBox);
  const tableImage = document.createElement('img');
  tableImage.setAttribute('src', './src/img/main/stol__menu.jpg');
  tableImage.classList.add('product_img');
  tableBox.appendChild(tableImage);
  const tableLink = document.createElement('a');
  tableLink.setAttribute('href', '#');
  tableBox.appendChild(tableLink);
  const tableName = document.createElement('p');
  tableName.textContent = 'Стол MENU';
  tableName.classList.add('item');
  tableLink.appendChild(tableName);
  const tableInfo = document.createElement('p');
  tableInfo.textContent = 'Для того чтобы трапезничать было приятно, необходим правильный обеденный стол.';
  tableInfo.classList.add('desc');
  tableBox.appendChild(tableInfo);
  const tableBoxPrice = document.createElement('div');
  tableBoxPrice.classList.add('box__price');
  tableBox.appendChild(tableBoxPrice);
  const tablePrice = document.createElement('p');
  tablePrice.textContent = '34 000 руб.';
  tablePrice.classList.add('price');
  tableBoxPrice.appendChild(tablePrice);
  const sofaAskestaBox = document.createElement("div");
  sofaAskestaBox.classList.add("product");
  productCatalogBox.appendChild(sofaAskestaBox);
  const sofaAskestaImage = document.createElement('img');
  sofaAskestaImage.setAttribute('src', './src/img/main/kreslo__askesta.jpg');
  sofaAskestaImage.classList.add('product_img');
  sofaAskestaBox.appendChild(sofaAskestaImage);
  const sofaAskestaLink = document.createElement('a');
  sofaAskestaLink.setAttribute('href', '#');
  sofaAskestaBox.appendChild(sofaAskestaLink);
  const sofaAskestaName = document.createElement('p');
  sofaAskestaName.textContent = 'Кресло ASKESTA';
  sofaAskestaName.classList.add('item');
  sofaAskestaLink.appendChild(sofaAskestaName);
  const sofaAskestaInfo = document.createElement('p');
  sofaAskestaInfo.textContent = 'Высокоэластичный пенополиуретан в «начинке» кресла надежен и долговечен';
  sofaAskestaInfo.classList.add('desc');
  sofaAskestaBox.appendChild(sofaAskestaInfo);
  const sofaAskestaBoxPrice = document.createElement('div');
  sofaAskestaBoxPrice.classList.add('box__price');
  sofaAskestaBox.appendChild(sofaAskestaBoxPrice);
  const sofaAskestaPrice = document.createElement('p');
  sofaAskestaPrice.textContent = '68 000 руб.';
  sofaAskestaPrice.classList.add('price');
  sofaAskestaBoxPrice.appendChild(sofaAskestaPrice);
  const tableNormanBox = document.createElement("div");
  tableNormanBox.classList.add("product");
  productCatalogBox.appendChild(tableNormanBox);
  const tableNormanImage = document.createElement('img');
  tableNormanImage.setAttribute('src', './src/img/main/stol__norman.jpg');
  tableNormanImage.classList.add('product_img');
  tableNormanBox.appendChild(tableNormanImage);
  const tableNormanLink = document.createElement('a');
  tableNormanLink.setAttribute('href', '#');
  tableNormanBox.appendChild(tableNormanLink);
  const tableNormanName = document.createElement('p');
  tableNormanName.textContent = 'Стол NORMAN';
  tableNormanName.classList.add('item');
  tableNormanLink.appendChild(tableNormanName);
  const tableNormanInfo = document.createElement('p');
  tableNormanInfo.textContent = 'Прекрасно переносит солнечные лучи, перепады влажности и любые осадки.';
  tableNormanInfo.classList.add('desc');
  tableNormanBox.appendChild(tableNormanInfo);
  const tableNormanBoxPrice = document.createElement('div');
  tableNormanBoxPrice.classList.add('box__price');
  tableNormanBox.appendChild(tableNormanBoxPrice);
  const tableNormanPrice = document.createElement('p');
  tableNormanPrice.textContent = '40 000 руб.';
  tableNormanPrice.classList.add('price');
  tableNormanBoxPrice.appendChild(tableNormanPrice);
  const sofaNastanBox = document.createElement("div");
  sofaNastanBox.classList.add("product");
  productCatalogBox.appendChild(sofaNastanBox);
  const sofaNastanImage = document.createElement('img');
  sofaNastanImage.setAttribute('src', './src/img/main/divan__nastan.jpg');
  sofaNastanImage.classList.add('product_img');
  sofaNastanBox.appendChild(sofaNastanImage);
  const sofaNastanLink = document.createElement('a');
  sofaNastanLink.setAttribute('href', '#');
  sofaNastanBox.appendChild(sofaNastanLink);
  const sofaNastanName = document.createElement('p');
  sofaNastanName.textContent = 'Диван NASTAN';
  sofaNastanName.classList.add('item');
  sofaNastanLink.appendChild(sofaNastanName);
  const sofaNastanInfo = document.createElement('p');
  sofaNastanInfo.textContent = 'Модель отличается простотой линий и форм, отсутствием броского декора.';
  sofaNastanInfo.classList.add('desc');
  sofaNastanBox.appendChild(sofaNastanInfo);
  const sofaNastanBoxPrice = document.createElement('div');
  sofaNastanBoxPrice.classList.add('box__price');
  sofaNastanBox.appendChild(sofaNastanBoxPrice);
  const sofaNastanPrice = document.createElement('p');
  sofaNastanPrice.textContent = '80 000 руб.';
  sofaNastanPrice.classList.add('price');
  sofaNastanBoxPrice.appendChild(sofaNastanPrice);
  const catalogLink = document.createElement('a');
  catalogLink.classList.add('catalog_link');
  catalogLink.addEventListener('click', (event) => {
    event.preventDefault();
    window.application.screens['catalogScreen'] = catalogScreen;
    window.application.renderScreen('catalogScreen');
  });
  catalogLink.textContent = 'Перейти в каталог';
  productCatalogBox.appendChild(catalogLink);
  mainBlockArray.forEach((element) => {
    container.appendChild(element);
  });
  footer(container);
}

function catalogBlock(container) {
  let catalogBlockArray = [];
  const catalogTop = document.createElement("div");
  catalogTop.classList.add("top_catalog", "center");
  catalogBlockArray.push(catalogTop);
  header(catalogTop);
  const catalogTitle = document.createElement("h1");
  catalogTitle.textContent = "Каталог";
  catalogTitle.classList.add("catalog_title", 'title');
  catalogTop.appendChild(catalogTitle);
  const catalogNavigation = document.createElement('div');
  catalogNavigation.classList.add('catalog_nav', 'center');
  catalogBlockArray.push(catalogNavigation);
  const navigationBox = document.createElement('nav');
  catalogNavigation.appendChild(navigationBox);
  const catalogMainLink = document.createElement('a');
  catalogMainLink.setAttribute('href', 'index.html');
  catalogMainLink.classList.add('breadcrumbs_link');
  navigationBox.appendChild(catalogMainLink);
  const catalogMainText = document.createElement('span');
  catalogMainText.classList.add('breadcrumbs_text');
  catalogMainText.textContent = 'Главная';
  catalogMainLink.appendChild(catalogMainText);
  const catalogCatalogLink = document.createElement('a');
  catalogCatalogLink.addEventListener('click', (event) => {
    event.preventDefault();
    window.application.screens['catalogScreen'] = catalogScreen;
    window.application.renderScreen('catalogScreen');
  });
  catalogCatalogLink.classList.add('breadcrumbs_link');
  navigationBox.appendChild(catalogCatalogLink);
  const catalogCatalogText = document.createElement('span');
  catalogCatalogText.classList.add('breadcrumbs_text');
  catalogCatalogText.textContent = 'Каталог товаров';
  catalogCatalogLink.appendChild(catalogCatalogText);
  const catalogSelect = document.createElement('div');
  catalogSelect.classList.add('select');
  catalogNavigation.appendChild(catalogSelect);
  const select = document.createElement('select');
  catalogSelect.appendChild(select);
  const selectValue1 = document.createElement('option');
  selectValue1.setAttribute('value', '1');
  selectValue1.textContent = 'Порядок: сперва новые';
  select.appendChild(selectValue1);
  const selectValue2 = document.createElement('option');
  selectValue2.setAttribute('value', '2');
  selectValue2.textContent = 'Порядок: сперва дорогие';
  select.appendChild(selectValue2);
  const selectValue3 = document.createElement('option');
  selectValue3.setAttribute('value', '3');
  selectValue3.textContent = 'Порядок: сперва дешевые';
  select.appendChild(selectValue3);
  const catalogProductBox = document.createElement('div');
  catalogProductBox.classList.add('product__box', 'center');
  catalogBlockArray.push(catalogProductBox);
  const catalogProductContent = document.createElement('div');
  catalogProductContent.classList.add('product_content');
  catalogProductBox.appendChild(catalogProductContent);
  tatran(catalogProductContent);
  vilora(catalogProductContent);
  menu(catalogProductContent);
  asketa(catalogProductContent);
  lunar(catalogProductContent);
  nastan(catalogProductContent);
  tatran(catalogProductContent);
  vilora(catalogProductContent);
  menu(catalogProductContent);
  asketa(catalogProductContent);
  lunar(catalogProductContent);
  nastan(catalogProductContent);
  const showMore = document.createElement('a');
  showMore.setAttribute('href', '#');
  showMore.classList.add('catalog_link');
  showMore.textContent = 'Показать ещё';
  catalogProductContent.appendChild(showMore);
  catalogBlockArray.forEach((element) => {
    container.appendChild(element);
  });
  footer(container);
}

function icons (element) {
  const icons = document.createElement("div");
  icons.classList.add("product_icons");
  const linkPocket = document.createElement("a");
  linkPocket.setAttribute("href", "#");
  icons.appendChild(linkPocket);
  const pocketImage = document.createElement("img");
  pocketImage.setAttribute("src", "./src/img/main/pocket.svg");
  pocketImage.classList.add('icon_hover');
  linkPocket.appendChild(pocketImage);
  const linkHeart = document.createElement("a");
  linkHeart.setAttribute("href", "#");
  icons.appendChild(linkHeart);
  const heartImage = document.createElement("img");
  heartImage.setAttribute("src", "./src/img/main/heart.svg");
  heartImage.classList.add('icon_hover');
  linkHeart.appendChild(heartImage);
  return element.appendChild(icons);
}

function tatran (element) {
  const tatranBad = document.createElement('div');
  tatranBad.classList.add('product');
  element.appendChild(tatranBad);
  icons(tatranBad);
  const tatranBadImage = document.createElement('img');
  tatranBadImage.setAttribute('src', './src/img/catalog/catalog_prod_1.jpg');
  tatranBadImage.classList.add('product_img');
  tatranBad.appendChild(tatranBadImage);
  const tatranBadLink = document.createElement('a');
  tatranBadLink.setAttribute('href', '#');
  tatranBad.appendChild(tatranBadLink);
  const tatranBadName = document.createElement('p');
  tatranBadName.textContent = 'Кровать TATRAN';
  tatranBadName.classList.add('item');
  tatranBadLink.appendChild(tatranBadName);
  const tatranBadInfo = document.createElement('p');
  tatranBadInfo.textContent = 'Основание из полированной нержавеющей стали, придает оригинальный парящий эффект.';
  tatranBadInfo.classList.add('desc');
  tatranBad.appendChild(tatranBadInfo);
  const boxPrice = document.createElement('div');
  boxPrice.classList.add('box__price');
  tatranBad.appendChild(boxPrice);
  const price = document.createElement('p');
  price.textContent = '120 000 руб.';
  price.classList.add('price');
  boxPrice.appendChild(price);
  return element.appendChild(tatranBad);
}

function vilora (element) {
  const vilora = document.createElement('div');
  vilora.classList.add('product');
  element.appendChild(vilora);
  const viloraImage = document.createElement('img');
  viloraImage.setAttribute('src', './src/img/catalog/catalog_prod_2.jpg');
  viloraImage.classList.add('product_img');
  vilora.appendChild(viloraImage);
  const viloraLink = document.createElement('a');
  viloraLink.setAttribute('href', '#');
  vilora.appendChild(viloraLink);
  const viloraName = document.createElement('p');
  viloraName.textContent = 'Кресло VILORA';
  viloraName.classList.add('item');
  viloraLink.appendChild(viloraName);
  const viloraInfo = document.createElement('p');
  viloraInfo.textContent = 'Мягкое и уютное, аккуратное и стильное. Упругие подушки сиденья и приятная на ощупь ткань.';
  viloraInfo.classList.add('desc');
  vilora.appendChild(viloraInfo);
  const boxPrice = document.createElement('div');
  boxPrice.classList.add('box__price');
  vilora.appendChild(boxPrice);
  const price = document.createElement('p');
  price.textContent = '21 000 руб.';
  price.classList.add('price');
  boxPrice.appendChild(price);
  return element.appendChild(vilora);
}

function menu (element) {
  const menu = document.createElement('div');
  menu.classList.add('product');
  element.appendChild(menu);
  const menuImage = document.createElement('img');
  menuImage.setAttribute('src', './src/img/catalog/catalog_prod_3.jpg');
  menuImage.classList.add('product_img');
  menu.appendChild(menuImage);
  const menuLink = document.createElement('a');
  menuLink.setAttribute('href', '#');
  menu.appendChild(menuLink);
  const menuName = document.createElement('p');
  menuName.textContent = 'Стол MENU';
  menuName.classList.add('item');
  menuLink.appendChild(menuName);
  const menuInfo = document.createElement('p');
  menuInfo.textContent = 'Для того чтобы трапезничать было приятно, необходим правильный обеденный стол.';
  menuInfo.classList.add('desc');
  menu.appendChild(menuInfo);
  const boxPrice = document.createElement('div');
  boxPrice.classList.add('box__price');
  menu.appendChild(boxPrice);
  const price = document.createElement('p');
  price.textContent = '34 000 руб.';
  price.classList.add('price');
  boxPrice.appendChild(price);
  return element.appendChild(menu);
}

function asketa (element) {
  const asketa = document.createElement('div');
  asketa.classList.add('product');
  element.appendChild(asketa);
  const asketaImage = document.createElement('img');
  asketaImage.setAttribute('src', './src/img/catalog/catalog_prod_4.jpg');
  asketaImage.classList.add('product_img');
  asketa.appendChild(asketaImage);
  const asketaLink = document.createElement('a');
  asketaLink.setAttribute('href', '#');
  asketa.appendChild(asketaLink);
  const asketaName = document.createElement('p');
  asketaName.textContent = 'Диван ASKESTA';
  asketaName.classList.add('item');
  asketaLink.appendChild(asketaName);
  const asketaInfo = document.createElement('p');
  asketaInfo.textContent = 'Благодаря защелкивающемуся механизму диван легко раскладывается в комфортную кровать.';
  asketaInfo.classList.add('desc');
  asketa.appendChild(asketaInfo);
  const boxPrice = document.createElement('div');
  boxPrice.classList.add('box__price');
  asketa.appendChild(boxPrice);
  const price = document.createElement('p');
  price.textContent = '68 000 руб.';
  price.classList.add('price');
  boxPrice.appendChild(price);
  return element.appendChild(asketa);
}

function lunar (element) {
  const lunar = document.createElement('div');
  lunar.classList.add('product');
  element.appendChild(lunar);
  const lunarImage = document.createElement('img');
  lunarImage.setAttribute('src', './src/img/catalog/catalog_prod_5.jpg');
  lunarImage.classList.add('product_img');
  lunar.appendChild(lunarImage);
  const lunarLink = document.createElement('a');
  lunarLink.setAttribute('href', '#');
  lunar.appendChild(lunarLink);
  const lunarName = document.createElement('p');
  lunarName.textContent = 'Кресло LUNAR';
  lunarName.classList.add('item');
  lunarLink.appendChild(lunarName);
  const lunarInfo = document.createElement('p');
  lunarInfo.textContent = 'Прекрасно переносит солнечные лучи, перепады влажности и любые осадки.';
  lunarInfo.classList.add('desc');
  lunar.appendChild(lunarInfo);
  const boxPrice = document.createElement('div');
  boxPrice.classList.add('box__price');
  lunar.appendChild(boxPrice);
  const price = document.createElement('p');
  price.textContent = '40 000 руб.';
  price.classList.add('price');
  boxPrice.appendChild(price);
  return element.appendChild(lunar);
}

function nastan (element) {
  const nastan = document.createElement('div');
  nastan.classList.add('product');
  element.appendChild(nastan);
  const nastanImage = document.createElement('img');
  nastanImage.setAttribute('src', './src/img/catalog/catalog_prod_6.jpg');
  nastanImage.classList.add('product_img');
  nastan.appendChild(nastanImage);
  const nastanLink = document.createElement('a');
  nastanLink.setAttribute('href', '#');
  nastan.appendChild(nastanLink);
  const nastanName = document.createElement('p');
  nastanName.textContent = 'Шкаф Nastan';
  nastanName.classList.add('item');
  nastanLink.appendChild(nastanName);
  const nastanInfo = document.createElement('p');
  nastanInfo.textContent = 'Мебель может быть оснащена разнообразными системами подсветки.';
  nastanInfo.classList.add('desc');
  nastan.appendChild(nastanInfo);
  const boxPrice = document.createElement('div');
  boxPrice.classList.add('box__price');
  nastan.appendChild(boxPrice);
  const price = document.createElement('p');
  price.textContent = '80 000 руб.';
  price.classList.add('price');
  boxPrice.appendChild(price);
  return element.appendChild(nastan);
}

function footer (element) {
  const footer = document.createElement('footer');
  footer.classList.add('footer', 'center');
  const footerLinkLogo = document.createElement('a');
  footerLinkLogo.setAttribute("href", "index.html");
  footerLinkLogo.classList.add('footer__logo');
  footer.appendChild(footerLinkLogo);
  const footerLogo = document.createElement('img');
  footerLogo.setAttribute('src', './src/img/footer/logo_footer.svg');
  footerLinkLogo.appendChild(footerLogo);
  const footerItems = document.createElement('div');
  footerItems.classList.add('footer_items');
  footer.appendChild(footerItems);
  const footerInfo = document.createElement('div');
  footerInfo.classList.add('footer_info');
  footerItems.appendChild(footerInfo);
  const footerMenu = document.createElement('nav');
  footerMenu.classList.add('footer__menu');
  footerInfo.appendChild(footerMenu);
  const footerMenuTitle = document.createElement('p');
  footerMenuTitle.classList.add('footer_text');
  footerMenuTitle.textContent = 'Меню';
  footerMenu.appendChild(footerMenuTitle);
  const footerMainLink = document.createElement('a');
  footerMainLink.setAttribute('href', 'index.html');
  footerMainLink.classList.add('footer_menu_item');
  footerMainLink.textContent = 'Главная';
  footerMenu.appendChild(footerMainLink);
  const footerCatalogLink = document.createElement('a');
  footerCatalogLink.addEventListener('click', (event) => {
    event.preventDefault();
    window.application.screens['catalogScreen'] = catalogScreen;
    window.application.renderScreen('catalogScreen');
  });
  footerCatalogLink.classList.add('footer_menu_item');
  footerCatalogLink.textContent = 'Каталог';
  footerMenu.appendChild(footerCatalogLink);
  const footerCartLink = document.createElement('a');
  footerCartLink.setAttribute('href', '#');
  footerCartLink.classList.add('footer_menu_item');
  footerCartLink.textContent = 'Корзина';
  footerMenu.appendChild(footerCartLink);
  const footerContacts = document.createElement('div');
  footerContacts.classList.add('footer__menu');
  footerItems.appendChild(footerContacts);
  const footerContactsTitle = document.createElement('p');
  footerContactsTitle.classList.add('footer_text');
  footerContactsTitle.textContent = 'Контакты';
  footerContacts.appendChild(footerContactsTitle);
  const footerPhoneLink = document.createElement('a');
  footerPhoneLink.setAttribute('href', 'tel:+79088008080');
  footerPhoneLink.classList.add('footer_menu_item');
  footerPhoneLink.textContent = '+7 908 800 80 80';
  footerContacts.appendChild(footerPhoneLink);
  const footerMailLink = document.createElement('a');
  footerMailLink.setAttribute('href', 'mailto:help@interier.com');
  footerMailLink.classList.add('footer_menu_item');
  footerMailLink.textContent = 'help@interier.com';
  footerContacts.appendChild(footerMailLink);
  const footerIcons = document.createElement('div');
  footerIcons.classList.add('icons');
  footerContacts.appendChild(footerIcons);
  const footerInstLogoLink = document.createElement('a');
  footerInstLogoLink.setAttribute('href', '#');
  footerIcons.appendChild(footerInstLogoLink);
  const footerInstLogo = document.createElement('img');
  footerInstLogo.classList.add('footer_icon')
  footerInstLogo.setAttribute('src', './src/img/footer/inst.svg');
  footerInstLogoLink.appendChild(footerInstLogo);
  const footerTwitterLogoLink = document.createElement('a');
  footerTwitterLogoLink.setAttribute('href', '#');
  footerIcons.appendChild(footerTwitterLogoLink);
  const footerTwitterLogo = document.createElement('img');
  footerTwitterLogo.classList.add('footer_icon')
  footerTwitterLogo.setAttribute('src', './src/img/footer/twitter.svg');
  footerTwitterLogoLink.appendChild(footerTwitterLogo);
  const footerFBLogoLink = document.createElement('a');
  footerFBLogoLink.setAttribute('href', '#');
  footerIcons.appendChild(footerFBLogoLink);
  const footerFBLogo = document.createElement('img');
  footerFBLogo.classList.add('footer_icon')
  footerFBLogo.setAttribute('src', './src/img/footer/fb.svg');
  footerFBLogoLink.appendChild(footerFBLogo);
  const footerForm = document.createElement('form');
  footerForm.setAttribute('action', '#');
  footerForm.classList.add('footer_form');
  footerItems.appendChild(footerForm);
  const footerNews = document.createElement('p');
  footerNews.classList.add('footer_news');
  footerNews.textContent = 'Получайте наши новости и обновления';
  footerForm.appendChild(footerNews);
  const footerInput = document.createElement('input');
  footerInput.setAttribute('type', 'email');
  footerInput.setAttribute('placeholder', 'Email Address');
  footerInput.classList.add('footer_input');
  footerForm.appendChild(footerInput);
  const footerButton = document.createElement('button');
  footerButton.setAttribute('type', 'submit');
  footerButton.classList.add('footer_button');
  footerButton.textContent = 'Подписаться';
  footerForm.appendChild(footerButton);
  return element.appendChild(footer);
}